server:  
    port: 8080
    session-timeout: 30  
    tomcat.max-threads: 450  
    tomcat.uri-encoding: UTF-8
  
spring:
  application:
    name: jackwang-spring-aop

  output:
    ansi:
      enabled: always

  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost
    port: 6379
    password: kF9wjNBC0IsxYuHW/lXDIw==
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）

  
  
  